### ISSUE TITLE
Создание игрового поля

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/checkers#1]
Написать функцию, которая будет возвращать игровое поле без фигур

**Comment by YuriyLyashko** [comment]
Прошу пробачення, але створене вами ігрове поле вже з фігурами. Якщо я не помиляюся.

**Comment by Denizantip** [comment]
Ага

**Comment by YuriyLyashko** [comment]
А... Сорі... Чекаю виконання завдання.
У початковому коді, мабуть, напрямок на "путь истинный", а я подумав, що вже створене поле та нанесені кольори.

**Comment by YuriyLyashko** [comment]
Пропоную видалити початкове розташування фігур. Так як воно являється не точним:
https://www.gambler.ru/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D1%85_%D1%88%D0%B0%D1%88%D0%B5%D0%BA

**Comment by Denizantip** [comment]
Присмотрись. Всё правильно. Просто доска находится к тебе чёрными фигурами. В клетке А - 1 находится шашка. Для решения алгоритма не должно иметь значения как находится доска

**Comment by YuriyLyashko** [comment]
Блін, або я шось не доганяю, або в твоїй розкладці на А-1 немає шашки )))
                                [['O', ' ', 'O', ' ', 'O', ' ', 'O', ' '],
                                [' ', 'O', ' ', 'O', ' ', 'O', ' ', 'O'],
                                ['O', ' ', 'O', ' ', 'O', ' ', 'O', ' '],
                                [' ', 'B', ' ', 'B', ' ', 'B', ' ', 'B'],
                                ['B', ' ', 'B', ' ', 'B', ' ', 'B', ' '],
                               [' ', 'X', ' ', 'X', ' ', 'X', ' ', 'X'],
                               ['X', ' ', 'X', ' ', 'X', ' ', 'X', ' '],
А-1 у мене тут ---> [' ', 'X', ' ', 'X', ' ', 'X', ' ', 'X']]

**Comment by Denizantip** [comment]
Там всё пронумеровано было . Нумерация идет сверху вниз. 'O' - Белые шашки. 'X' - Чёрные. ' '- Белые клетки. 'B' - черные клетки.
