### ISSUE TITLE
Определение цвета клетки

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/checkers#2]
Написать функцию, которая для заданной клетки возвращает ее цвет. Клетка задается координатами 0..7 начиная с левого верхнего угла

**Comment by YuriyLyashko** [comment]
Привіт. Добав свій код в основний файл Checkers.

**Comment by yu-shvets** [comment]
Привет. Я добавил. Функция называется color_of_square. В master  создал свою версию с самого начала - board... - создание чистой доски, определение цвета полей, расстановка шашек, вывод на экран.

**Comment by YuriyLyashko** [comment]
Намагаюся підвязатися до твоєї функції, для обмеження руху шашки тільки по чорним полям, але color_board не повертає кольору клітинки по заданим координатам checks[y][x]. Де у - рядок, а х - стовпчик від 0 до 7.

**Comment by YuriyLyashko** [comment]
упс, не на ту ф-цію глянув. З color_of_square все гуд ).
