### ISSUE TITLE
Проверка возможности взятия

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/checkers#23]
Модифицировать функцию, которая проверяет возможно ли взятие на всем поле  с учетом правил взятия для дамок

**Comment by YuriyLyashko** [comment]
У нас немає функції, яка перевіряє можливість взяття на всьому полі. (якщо не помиляюся).
Є функція, яка повертає список клітинок після взяття для певного кольору.
І є функція, яка перевіряє можливість взяття для шашки.
Дик, яку із них модифікувати?

**Comment by YuriyLyashko** [comment]
Точніше, є функція, яка перевіряє можливість взяття для початкових та кінцевих координат (звичайної шашки)

**Comment by YuriyLyashko** [comment]
бо, у мене вимальовується кілька ф-цій для дамки, аналогічних тим, що є для звичайних шашок:
- список клітинок після взяття для стартових координат;
- список клітинок після взяття для заданого кольору;
- перевірка наявності можливості взяття для шашок та дамок
