### ISSUE TITLE
Направление хода

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/checkers#5]
Написать функцию, которая в зависимости от цвета шашки будет возращать направление хода

**Comment by YuriyLyashko** [comment]
Якщо вже є щось по цій функції, то скинь будь ласка. Я вже закомітив демо функцію можливості ходу, а там необхідне посилання на функцію напрямку ходу. Треба все узгодити.

**Comment by shevchukproject** [comment]
Сьогодні планую завершити функцію. Відпишу, як все буде.

**Comment by shevchukproject** [comment]
Загрузив функцію
