### ISSUE TITLE
Валидация границ

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/checkers#7]
Написать функцию для проверки, попадают ли заданные координаты в пределы поля

**Comment by YuriyLyashko** [comment]
функція check_falling_into_field дозволяє задавати відємні координати
наприклад: [4, -1]
при перевірці потрапляння в поле координат, що обчислюються в інших ф-ціях вказані координати проходять перевірку!

**Comment by YuriyLyashko** [comment]
вніс перевірку на < 0
